/* eslint-disable @next/next/no-img-element */
import Head from 'next/head';
import CartBTN from './button/CartBTN';
import CategoryBTN from './button/CategoryBTN';
import HomeBTN from './button/HomeBTN';
import ProfileBTN from './button/ProfileBTN';
import WishlistBTN from './button/WishlistBTN';
import TopNav from './TopNav';

interface Props {
  children: any;
  title?: string;
}

function Layout({ title, children }: Props) {
  return (
    <>
      <Head>
        <title>
          {title ? title + ' | DiPMart Ecommerce' : 'DiPMart Ecommerce'}
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="main-layout">
        <TopNav />
        <main className="container m-auto mt-4 px-4">{children}</main>
        <footer className="grid grid-cols-5 gap-10  h-auto shadow-inner  sticky bottom-0 bg-white py-3 px-5 text-center z-50">
          <HomeBTN />
          <CategoryBTN />
          <CartBTN />
          <WishlistBTN />
          <ProfileBTN />
        </footer>
      </div>
    </>
  );
}

export default Layout;
