import Head from 'next/head';
import Link from 'next/link';
import HomeBTN from './button/HomeBTN';

interface Props {
  children: any;
  title?: string;
}

function Layout({ title, children }: Props) {
  return (
    <>
      <Head>
        <title>
          {title ? title + ' | DiPMart Ecommerce' : 'DiPMart Ecommerce'}
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="main-layout">
        <header>
          <nav className="nav">
            <Link href={'/'}>
              <a className="text-lg font-bold">DiPMart</a>
            </Link>
            <div>
              <Link href={'/cart'}>
                <a className="px-4">Cart</a>
              </Link>
              <Link href={'/login'}>
                <a className="px-4">Login</a>
              </Link>
            </div>
          </nav>
        </header>
        <main className="container m-auto mt-4 px-4">{children}</main>
        <footer className="flex justify-center h-auto shadow-inner items-center sticky bottom-0 bg-white py-3">
          <HomeBTN />
        </footer>
      </div>
    </>
  );
}

export default Layout;
